#!/bin/bash
# vi: set sw=4 ts=4 ai:

# Determine the program name and the 'running directory'
IAM="${0##*/}"
CRD="$( [[ "${0:0:2}" = "./" ]] &&
	{	printf "${PWD}/${0#./}"
	} || {
		printf "${0}"
	})"
CRD="${CRD%/*}"
CUR="${PWD}"

# Make sure all language settings are correct
export LANG=C

# Set and unset the needed shell settings
set +o noclobber        # Overwrite existing files, if needed
set -o nounset          # Do not allow uninitialized variables
set +o errexit          # No returncode checking

# Find the current version
VERSION=$(awk '$1 == "version:" { print $2 }' ${CRD}/galaxy.yml)

cd ${CRD}/docs
make															&& \
cd ${CRD}														&& \
tox																&& \
	ansible-galaxy collection build -f --output-path=..			&& \
	ansible-galaxy collection install -f ../ansilabnl-micetro-${VERSION}.tar.gz
