---
#
# Set, delete and change custom properties on Men&Mice Micetro example
#
# The file <ansible_topdir>/group_vars/all contains:
#
#    ---
#    mm_provider:
#      mm_url: http://mmsuite.example.net
#      mm_user: apiuser
#      mm_password: apipasswd
#
- name: Men&Mice Micetro Custom Properties test play
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Ansible information
      ansible.builtin.debug:
        msg:
          - "Ansible version   : {{ ansible_version.full }}"
          - "Python version    : {{ ansible_facts['python_version'] }}"
          - "Python executable : {{ ansible_facts['python']['executable'] }}"

    - name: Set text property
      ansilabnl.micetro.props:
        state: present
        name: MyProperty
        proptype: text
        dest: dnsserver
        listitems:
          - John
          - Paul
          - Ringo
          - George
        mm_provider: "{{ mm_provider }}"
      delegate_to: localhost

    - name: Check idempotentie
      ansilabnl.micetro.props:
        state: present
        name: MyProperty
        proptype: text
        dest: dnsserver
        listitems:
          - John
          - Paul
          - Ringo
          - George
        mm_provider: "{{ mm_provider }}"
      delegate_to: localhost

    - name: Change type - not allowed
      ansilabnl.micetro.props:
        state: present
        name: MyProperty
        proptype: yesno
        dest: dnsserver
        listitems:
          - John
          - Paul
          - Ringo
          - George
        mm_provider: "{{ mm_provider }}"
      delegate_to: localhost

    - name: Change list around
      ansilabnl.micetro.props:
        state: present
        name: MyProperty
        proptype: text
        dest: dnsserver
        listitems:
          - George
          - John
          - Paul
          - Ringo
        mm_provider: "{{ mm_provider }}"
      delegate_to: localhost

    - name: Remove property
      ansilabnl.micetro.props:
        state: absent
        name: MyProperty
        proptype: text
        dest: dnsserver
        mm_provider: "{{ mm_provider }}"
      delegate_to: localhost

    - name: Remove property - again
      ansilabnl.micetro.props:
        state: absent
        name: MyProperty
        proptype: yesno
        dest: dnsserver
        mm_provider: "{{ mm_provider }}"
      delegate_to: localhost
