[#_managing_playbooks]
== Example playbooks

To use Men&Mice Micetro Ansible Integration you need to create Ansible
playbooks that utilize the functionality of Men&Mice Micetro.

Following are a couple of example playbooks for inspiration.

These playbooks have been tested extensively with different operating
systems, versions of Ansible and Python. For a complete overview, have
a look at the "<<README_testmatrix.adoc#testmatrix,Testmatrix>>" chapter.

Caveat: As the operating systems do not have all these combinations of
Ansible and Python available, the tests where done in Python virtual
environments.

All these playbooks are available in the `examples` directory.

[#_play_user]
=== play-user

.Add, delete or change a user
[source,yaml]
----
include::{sourcedir}/examples/play-user.yml[]
----

[#_play_group]
=== play-group

.Add, delete or change a group
[source,yaml]
----
include::{sourcedir}/examples/play-group.yml[]
----

[#_play_role]
=== play-role

.Add, delete or change a role
[source,yaml]
----
include::{sourcedir}/examples/play-role.yml[]
----

[#_play_props]
=== play-props

.Add, delete or change custom properties on assets
[source,yaml]
----
include::{sourcedir}/examples/play-props.yml[]
----

[#_play_claimip]
=== play-claimip

.Claim IP addresses in one or more ranges
[source,yaml]
----
include::{sourcedir}/examples/play-claimip.yml[]
----

[#_play_dhcp]
=== play-dhcp

.Make and release DHCP reservations
[source,yaml]
----
include::{sourcedir}/examples/play-dhcp.yml[]
----

[#_play_zone]
=== play-zone

.Add, delete or change a DNS zone
[source,yaml]
----
include::{sourcedir}/examples/play-zone.yml[]
----

[#_play_dnsrecord]
=== play-dnsrecord

.Add and change a DNS record
[source,yaml]
----
include::{sourcedir}/examples/play-dnsrecord.yml[]
----

[#_play_freeip]
=== play-freeip

.Find free IP addresses in a range or ranges
[source,yaml]
----
include::{sourcedir}/examples/play-freeip.yml[]
----

[#_play_ipinfo]
=== play-ipinfo

.Collect a lot of info concerning an IP address
[source,yaml]
----
include::{sourcedir}/examples/play-ipinfo.yml[]
----

[#_play_all]
=== play_it_all

.Example of a playbook that combines functionality
[source,yaml]
----
include::{sourcedir}/examples/play_it_all.yml[]
----
