=== ansilabnl.micetro.inventory plugin

This plugin generates the inventory from Men&Mice Micetro. It supports reading
configuration from both a YAML configuration file and environment variables. If
reading from the YAML file, the filename must end with
`ansilabnl.micetro.inventory.(yml|yaml)`, the path in the command would be
`/path/to/ansilabnl.micetro.inventory.(yml|yaml)`. If some arguments in the
configuration file are missing, this plugin will try to fill in the missing
arguments by reading from environment variables. If reading configurations from
environment variables, the path in the command must be
`@ansilabnl.micetro.inventory`.

Valid configuration filenames are:

* `ansilabnl.micetro.inventory`
* `mmsuite`
* `mandm`
* `menandmice`
* `mandmsuite`
* `ansilabnl.micetro.suite`
* `mandm_suite`

==== Options

There are two sets of configuration options, the options for the
inventory plugin to function correctly and for Ansible to know how to
use the plugin.

===== Plugin configuration

The `ansilabnl.micetro.inventory` plugin is configured through a configuration file,
named `ansilabnl.micetro.inventory.yml` and the options are:

* plugin: Name of the plugin (`ansilabnl.micetro.inventory`)
* host: Men&Mice Micetro to connect to (`http://mmsuite.example.net`)
* user: UserID to connect with (`apiuser`)
* password: The password to connect with (`apipasswd`)
* filters: Filter on custom properties, can be more than 1 and should be
a list. If multiple filters are given, they act as an *and* function
* ranges: What IP ranges to examine (`172.16.17.0/24`) Multiple ranges
can be given, they act as an *or* function

When both _ranges_ and _filters_ are supplied that will result in an
*and* function.

Example:

[source,yaml]
----
filters:
  - location: home
  - owner: tonk
ranges:
  - 192.168.4.0/24
  - 172.16.17.0/24
----

Would result in an inventory for all host that have the `location: home`
*and* `owner: tonk` custom properties set *and* are either a member of
the `192.168.4.0/24` *or* `172.16.17.0/24` range.

An example of the `ansilabnl.micetro.inventory.yml` file:

[source,yaml]
----
plugin: ansilabnl.micetro.inventory
host: "http://mmsuite.example.net"
user: apiuser
password: apipasswd
filters:
  - location: London
ranges:
  - 172.16.17.0/24
----

===== Environment variables:

The `ansilabnl.micetro.inventory` plugin can also be configured through environment
variables

....
export MICETRO_HOST=YOUR_MICETRO_HOST_ADDRESS
export MICETRO_USER=YOUR_MICETRO_USER
export MICETRO_PASSWORD=YOUR_MICETRO_PASSWORD
export MICETRO_FILTERS=YOUR_MICETRO_FILTERS
export MICETRO_RANGES=YOUR_MICETRO_RANGES
....

When reading configuration from the environment, the inventory path must
always be `@ansilabnl.micetro.inventory`.

[source,bash]
----
ansible-inventory -i @ansilabnl.micetro.inventory --list
----

===== Ansible configuration

Ansible needs to know about the `ansilabnl.micetro.inventory` plugin and also has some
extra configuration options. First the `ansilabnl.micetro.inventory` plugin needs to be
enabled, so Ansible can use it. This is done in the `[inventory]`
section in the `ansible.cfg` file.

....
[inventory]
enable_plugins   = ansilabnl.micetro.inventory, host_list, auto
cache            = yes
cache_plugin     = jsonfile
cache_prefix     = ansilabnl.micetro.inv
cache_timeout    = 3600
cache_connection = /tmp/ansilabnl.micetro.inventory_cache
....

With the following meaning:

* `cache`: Switch caching on and off
* `cache_plugin`: Which caching plugin to use
** `jsonfile`
** `yaml`
** `pickle`
** …
* `cache_prefix`: User defined prefix to use when creating the cache
files
* `cache_connection`: Path in which the cache plugin will save the cache
files
* `cache_timeout`: Timeout for the cache in seconds

Now the inventory plugin can be used with Ansible, like:

[source,bash]
----
ansible-inventory -i /path/to/ansilabnl.micetro.inventory.yml --list
----

Or set the `ansilabnl.micetro.inventory.yml` as the Ansible inventory in the
`ansible.cfg` file.

[source,bash]
----
inventory = ansilabnl.micetro.inventory.yml
----
